#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Report generation module for contrast analysis results.
对比度分析结果报告生成模块

Supports multiple output formats: JSON, Markdown, HTML, and plain text.
支持多种输出格式：JSON、Markdown、HTML和纯文本
"""

import json
from datetime import datetime
from typing import List, Optional, Dict, Any
from pathlib import Path

from .contrast import ContrastResult, Color, WCAGLevel
from .colorblind import SimulationResult, ColorBlindnessType


class ReportGenerator:
    """
    Multi-format report generator.
    多格式报告生成器
    
    Generates reports in JSON, Markdown, HTML, and plain text formats.
    """
    
    def __init__(self, language: str = "zh"):
        """
        Initialize the report generator.
        
        Args:
            language: Language for report content ("zh" or "en")
        """
        self.language = language
        self.timestamp = datetime.now().isoformat()
    
    def generate_json(self, results: List[ContrastResult], 
                      colorblind_results: Optional[Dict] = None,
                      suggestions: Optional[Dict] = None) -> str:
        """
        Generate JSON format report.
        生成JSON格式报告
        
        Args:
            results: List of contrast check results
            colorblind_results: Optional color blindness simulation results
            suggestions: Optional color suggestions
        
        Returns:
            JSON string
        """
        report = {
            "metadata": {
                "generated_at": self.timestamp,
                "tool": "ColorScope-CLI",
                "version": "1.0.0",
            },
            "contrast_results": [r.to_dict() for r in results],
        }
        
        if colorblind_results:
            report["colorblind_simulation"] = {
                k: [sr.to_dict() for sr in v] if isinstance(v, list) else v.to_dict()
                for k, v in colorblind_results.items()
            }
        
        if suggestions:
            report["suggestions"] = suggestions
        
        return json.dumps(report, indent=2, ensure_ascii=False)
    
    def generate_markdown(self, results: List[ContrastResult],
                          colorblind_results: Optional[Dict] = None,
                          suggestions: Optional[Dict] = None,
                          title: str = "ColorScope Contrast Report") -> str:
        """
        Generate Markdown format report.
        生成Markdown格式报告
        
        Args:
            results: List of contrast check results
            colorblind_results: Optional color blindness simulation results
            suggestions: Optional color suggestions
            title: Report title
        
        Returns:
            Markdown string
        """
        lines = []
        
        # Header
        lines.append(f"# {title}")
        lines.append("")
        lines.append(f"> Generated by ColorScope-CLI at {self.timestamp}")
        lines.append("")
        
        # Summary
        lines.append("## 📊 Summary")
        lines.append("")
        total = len(results)
        passed_aa = sum(1 for r in results if r.aa_normal)
        passed_aaa = sum(1 for r in results if r.aaa_normal)
        
        lines.append(f"| Metric | Count | Percentage |")
        lines.append(f"|--------|-------|------------|")
        lines.append(f"| Total Checks | {total} | 100% |")
        lines.append(f"| AA Compliant | {passed_aa} | {passed_aa/total*100:.1f}%" if total > 0 else "| AA Compliant | 0 | 0% |")
        lines.append(f"| AAA Compliant | {passed_aaa} | {passed_aaa/total*100:.1f}%" if total > 0 else "| AAA Compliant | 0 | 0% |")
        lines.append("")
        
        # Detailed Results
        lines.append("## 🎨 Contrast Results")
        lines.append("")
        lines.append("| Foreground | Background | Ratio | AA | AAA | Level |")
        lines.append("|------------|------------|-------|-----|------|-------|")
        
        for result in results:
            aa_status = "✅" if result.aa_normal else "❌"
            aaa_status = "✅" if result.aaa_normal else "❌"
            lines.append(
                f"| {result.foreground.to_hex()} | {result.background.to_hex()} | "
                f"{result.ratio:.2f}:1 | {aa_status} | {aaa_status} | {result.wcag_level.value} |"
            )
        lines.append("")
        
        # Color Blindness Simulation
        if colorblind_results:
            lines.append("## 👁️ Color Blindness Simulation")
            lines.append("")
            lines.append("Simulated appearance for users with different types of color vision deficiency:")
            lines.append("")
            
            for blindness_type, sim_results in colorblind_results.items():
                lines.append(f"### {blindness_type.title()}")
                lines.append("")
                if isinstance(sim_results, list):
                    for sr in sim_results:
                        lines.append(f"- Original: {sr.original.to_hex()} → Simulated: {sr.simulated.to_hex()}")
                else:
                    lines.append(f"- {sim_results.description}")
                lines.append("")
        
        # Suggestions
        if suggestions:
            lines.append("## 💡 Suggestions")
            lines.append("")
            if "foreground_suggestions" in suggestions:
                lines.append("### Foreground Adjustments")
                lines.append("")
                for sug in suggestions["foreground_suggestions"][:3]:
                    lines.append(f"- {sug['original']} → {sug['suggested']} (Ratio: {sug['new_ratio']:.2f}:1)")
                lines.append("")
            
            if "background_suggestions" in suggestions:
                lines.append("### Background Adjustments")
                lines.append("")
                for sug in suggestions["background_suggestions"][:3]:
                    lines.append(f"- {sug['original']} → {sug['suggested']} (Ratio: {sug['new_ratio']:.2f}:1)")
                lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by [ColorScope-CLI](https://github.com/yourusername/colorscope-cli)*")
        
        return "\n".join(lines)
    
    def generate_html(self, results: List[ContrastResult],
                      colorblind_results: Optional[Dict] = None,
                      suggestions: Optional[Dict] = None,
                      title: str = "ColorScope Contrast Report") -> str:
        """
        Generate HTML format report.
        生成HTML格式报告
        
        Args:
            results: List of contrast check results
            colorblind_results: Optional color blindness simulation results
            suggestions: Optional color suggestions
            title: Report title
        
        Returns:
            HTML string
        """
        html_parts = []
        
        # HTML Header
        html_parts.append("""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            background: white;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #333;
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #555;
            margin-top: 30px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background: #4CAF50;
            color: white;
        }}
        tr:hover {{
            background: #f5f5f5;
        }}
        .color-swatch {{
            display: inline-block;
            width: 24px;
            height: 24px;
            border-radius: 4px;
            vertical-align: middle;
            margin-right: 8px;
            border: 1px solid #ddd;
        }}
        .pass {{
            color: #4CAF50;
            font-weight: bold;
        }}
        .fail {{
            color: #f44336;
            font-weight: bold;
        }}
        .ratio {{
            font-family: monospace;
            font-size: 1.1em;
        }}
        .summary-card {{
            background: #f9f9f9;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
        }}
        .stat {{
            display: inline-block;
            margin-right: 40px;
        }}
        .stat-value {{
            font-size: 2em;
            font-weight: bold;
            color: #4CAF50;
        }}
        .stat-label {{
            color: #666;
            font-size: 0.9em;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🎨 {title}</h1>
        <p><em>Generated by ColorScope-CLI at {timestamp}</em></p>
""".format(title=title, timestamp=self.timestamp))
        
        # Summary
        total = len(results)
        passed_aa = sum(1 for r in results if r.aa_normal)
        passed_aaa = sum(1 for r in results if r.aaa_normal)
        
        html_parts.append("""
        <div class="summary-card">
            <h2>📊 Summary</h2>
            <div class="stat">
                <div class="stat-value">{total}</div>
                <div class="stat-label">Total Checks</div>
            </div>
            <div class="stat">
                <div class="stat-value" style="color: #4CAF50;">{passed_aa}</div>
                <div class="stat-label">AA Compliant</div>
            </div>
            <div class="stat">
                <div class="stat-value" style="color: #2196F3;">{passed_aaa}</div>
                <div class="stat-label">AAA Compliant</div>
            </div>
        </div>
""".format(total=total, passed_aa=passed_aa, passed_aaa=passed_aaa))
        
        # Results Table
        html_parts.append("""
        <h2>🎨 Contrast Results</h2>
        <table>
            <thead>
                <tr>
                    <th>Foreground</th>
                    <th>Background</th>
                    <th>Ratio</th>
                    <th>AA</th>
                    <th>AAA</th>
                    <th>Level</th>
                </tr>
            </thead>
            <tbody>
""")
        
        for result in results:
            aa_class = "pass" if result.aa_normal else "fail"
            aaa_class = "pass" if result.aaa_normal else "fail"
            aa_text = "✅ Pass" if result.aa_normal else "❌ Fail"
            aaa_text = "✅ Pass" if result.aaa_normal else "❌ Fail"
            
            html_parts.append("""
                <tr>
                    <td>
                        <span class="color-swatch" style="background: {fg};"></span>
                        <code>{fg_hex}</code>
                    </td>
                    <td>
                        <span class="color-swatch" style="background: {bg};"></span>
                        <code>{bg_hex}</code>
                    </td>
                    <td class="ratio">{ratio:.2f}:1</td>
                    <td class="{aa_class}">{aa_text}</td>
                    <td class="{aaa_class}">{aaa_text}</td>
                    <td>{level}</td>
                </tr>
""".format(
                fg=result.foreground.to_hex(),
                fg_hex=result.foreground.to_hex(),
                bg=result.background.to_hex(),
                bg_hex=result.background.to_hex(),
                ratio=result.ratio,
                aa_class=aa_class,
                aaa_class=aaa_class,
                aa_text=aa_text,
                aaa_text=aaa_text,
                level=result.wcag_level.value,
            ))
        
        html_parts.append("""
            </tbody>
        </table>
""")
        
        # Footer
        html_parts.append("""
        <div class="footer">
            <p>Generated by <a href="https://github.com/yourusername/colorscope-cli">ColorScope-CLI</a></p>
        </div>
    </div>
</body>
</html>
""")
        
        return "\n".join(html_parts)
    
    def generate_text(self, results: List[ContrastResult],
                      colorblind_results: Optional[Dict] = None,
                      suggestions: Optional[Dict] = None) -> str:
        """
        Generate plain text format report.
        生成纯文本格式报告
        
        Args:
            results: List of contrast check results
            colorblind_results: Optional color blindness simulation results
            suggestions: Optional color suggestions
        
        Returns:
            Plain text string
        """
        lines = []
        
        lines.append("=" * 60)
        lines.append("ColorScope Contrast Report")
        lines.append("=" * 60)
        lines.append(f"Generated: {self.timestamp}")
        lines.append("")
        
        # Summary
        total = len(results)
        passed_aa = sum(1 for r in results if r.aa_normal)
        passed_aaa = sum(1 for r in results if r.aaa_normal)
        
        lines.append("SUMMARY")
        lines.append("-" * 40)
        lines.append(f"Total Checks:     {total}")
        lines.append(f"AA Compliant:     {passed_aa} ({passed_aa/total*100:.1f}%)" if total > 0 else "AA Compliant:     0")
        lines.append(f"AAA Compliant:    {passed_aaa} ({passed_aaa/total*100:.1f}%)" if total > 0 else "AAA Compliant:    0")
        lines.append("")
        
        # Results
        lines.append("CONTRAST RESULTS")
        lines.append("-" * 40)
        
        for result in results:
            aa_status = "PASS" if result.aa_normal else "FAIL"
            aaa_status = "PASS" if result.aaa_normal else "FAIL"
            
            lines.append(f"FG: {result.foreground.to_hex()}  BG: {result.background.to_hex()}")
            lines.append(f"  Ratio: {result.ratio:.2f}:1  AA: {aa_status}  AAA: {aaa_status}")
            lines.append(f"  Level: {result.wcag_level.value}")
            lines.append("")
        
        lines.append("=" * 60)
        
        return "\n".join(lines)
    
    def save_report(self, content: str, filepath: str, format: str = "json"):
        """
        Save report to file.
        保存报告到文件
        
        Args:
            content: Report content
            filepath: Output file path
            format: Output format (json, md, html, txt)
        """
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        
        return str(path.absolute())
